const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {pointAction}=require('../web/lasso-geometry.js');
let p={points:[[0,0],[1,0],[1,1]],closed:false};
assert.deepEqual(pointAction(p,[0,1],100,100,{add:true}),{type:'insert',index:3});
assert.equal(pointAction(p,[0,0],100,100).type,'close');
assert.deepEqual(pointAction(p,[1,0],100,100,{remove:true}),{type:'remove',index:1});
assert.equal(pointAction(p,[.5,.5],100,100,{remove:true}).type,'none');
p.closed=true;
assert.deepEqual(pointAction(p,[.5,.5],100,100,{add:true}),{type:'insert',index:3});
assert.deepEqual(pointAction(p,[.5,0],100,100,{add:true}),{type:'insert',index:1});
assert.equal(pointAction(p,[1,1],100,100,{remove:true,add:true}).type,'remove');
assert.equal(pointAction(p,[1,1],100,100).type,'drag');
assert.equal(pointAction({points:[],closed:false},[.5,.5],100,100,{remove:true}).type,'none');
// Vertex hit radius is measured in visible pixels, not normalized source units.
assert.equal(pointAction(p,[.91,0],100,1000,{remove:true}).type,'remove');
assert.equal(pointAction(p,[1,.02],100,1000,{remove:true}).type,'none');
const text=fs.readFileSync(require.resolve('../web/app.js'),'utf8');
const code=text.slice(text.indexOf('const completionSounds='),text.indexOf('function renderJobs()'));
let frames=[],requests=[];
const context={document:{visibilityState:'visible',addEventListener(){}},colorWaiting:null,colorNext:null,requestAnimationFrame:fn=>frames.push(fn),api:(path,data)=>{requests.push(data.job);return Promise.resolve({})}};
vm.createContext(context);vm.runInContext(code,context);
vm.runInContext("completionSounds.add('one');flushCompletionSounds();flushCompletionSounds()",context);
assert.equal(frames.length,1);assert.equal(requests.length,0);
frames.shift()();assert.equal(requests.length,0);
frames.shift()();assert.deepEqual(requests,['one']);
vm.runInContext('flushCompletionSounds()',context);assert.equal(frames.length,0);
context.colorWaiting={};vm.runInContext("completionSounds.add('two');flushCompletionSounds()",context);assert.equal(frames.length,0);
context.colorWaiting=null;context.document.visibilityState='hidden';vm.runInContext('flushCompletionSounds()',context);assert.equal(frames.length,0);
context.document.visibilityState='visible';vm.runInContext('flushCompletionSounds()',context);frames.shift()();frames.shift()();assert.deepEqual(requests,['one','two']);
console.log('PASS: lasso point actions and paint-before-sound ordering');
