function legacyShortcut(){ /* Replaced by commands.js central registry. */ }
'use strict';
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
let reviewImg=null,reviewPreview=null;
let outputDraft=null, comparisonImg=null, comparisonKind='mask', loadSequence=0, previewSequence=0;
let app, batch, current, selected=null, busy=false, mode='image', brush='move', before=false, workImg=null, maskImg=null, originalImg=null, draft=null, preview=null, cutPreview=null, overlay=null, editTimer=null, editPending=false, drag=null, stroke=null, headRect=null, headStart=null, curveDrag=-1, viewShift={x:0,y:0}, displayedJobs=new Set(), polling=false, appendImport=true, hoveredPortraitId=null;
const RANGE_NAMES=['red','yellow','green','cyan','blue','magenta'];
const neutralRanges=()=>Object.fromEntries(RANGE_NAMES.map(name=>[name,{hue:0,saturation:0,lightness:0}]));
const neutral=()=>({rgb:[[0,0],[1,1]],red:[[0,0],[1,1]],green:[[0,0],[1,1]],blue:[[0,0],[1,1]],hue:0,saturation:0,lightness:0,shadows:0,highlights:0,temperature:0,tint:0,exposure:0,grain:0,color_ranges:neutralRanges()});
function message(text,error=false){$('toast').textContent=text;$('toast').className=error?'error':'';$('toast').hidden=false;clearTimeout(message.timer);message.timer=setTimeout(()=>$('toast').hidden=true,error?9000:5000)}
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Glass-Token':app?.token||''},body:JSON.stringify(data||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Operation failed');return d}
function context(extra={}){if(!current)throw Error('Import or select an image first');return {batch:batch.id,id:current.id,...extra}}
function guarded(fn){return async(...args)=>{try{await fn(...args)}catch(e){message(e.message,true)}}}
function isDraft(){return current&&draft&&JSON.stringify(draft)!==JSON.stringify(current.color)}
function schedule(){editPending=true;clearTimeout(editTimer);editTimer=setTimeout(()=>flush().catch(e=>message(e.message,true)),400);$('sessionStatus').textContent='Saving session…'}
async function flush(){clearTimeout(editTimer);if(!editPending||!current)return;const d=context({draft,transform:current.transform});await api('/api/edit',d);editPending=false;$('sessionStatus').textContent='Session autosaved'}
async function loadImage(url){const im=new Image();im.src=url;await im.decode();return im}
function imageURL(f,kind='work',thumb=false){return '/api/image?'+new URLSearchParams({batch:f.batch,id:f.id,kind,v:f.revision+'-'+f.work_stamp, ...(thumb?{thumb:'1'}:{})})}
async function refresh(force=false){const r=await fetch('/api/state');if(!r.ok)throw Error('Could not read the saved session');const firstLoad=!app;app=await r.json();if(firstLoad)for(const j of app.jobs||[])if(j.status!=='running')displayedJobs.add(j.id);batch=app.batches[app.active];renderBatch();renderOutput();renderJobs();
 if(!batch?.files.length){++previewSequence;current=null;selected=null;workImg=null;reviewImg=null;reviewPreview=null;preview=null;cutPreview=null;maskImg=null;$('empty').hidden=false;$('filename').textContent='Your next headshot starts here';$('filePosition').textContent='Import a ZIP or images to begin';$('sourceSize').textContent='—';$('loupe').hidden=true;draw();flushCompletionSounds();return}
 const f=batch.files.find(x=>x.id===selected)||batch.files[0];const change=force||!current||f.id!==current.id||f.revision!==current.revision||f.work_stamp!==current.work_stamp;
 if(change&&!editPending&&!drag){selected=f.id;current=clone(f);draft=clone(f.draft||f.color);await loadSelected();renderBatch()}
 await syncVoiceSelection();
 flushCompletionSounds();
}
async function syncVoiceSelection(){
 if(!batch||!current||busy||current.batch!==batch.id||!batch.files.some(f=>f.id===current.id)||batch.selected_id===current.id)return;
 const target=batch,id=current.id;
 await api('/api/selection',{batch:target.id,id});
 target.selected_id=id;
}
function renderBatch(){const signature=JSON.stringify([app.active,selected,Object.values(app.batches).map(b=>[b.id,b.name]),(batch?.files||[]).map(f=>[f.id,f.name,f.width,f.height,f.revision,f.work_stamp,f.saved,f.pending_color,f.mask_applied,f.mask])]);if(renderBatch.signature===signature)return;renderBatch.signature=signature;const select=$('batchSelect');select.replaceChildren();for(const b of Object.values(app.batches)){const o=new Option(b.name,b.id,b.id===app.active,b.id===app.active);select.add(o)}
 const queueScroll={top:$('queue').scrollTop,left:$('queue').scrollLeft};$('queue').replaceChildren();const files=batch?.files||[];$('batchCount').textContent='Portraits · '+files.length;$('savedCount').textContent=files.length?files.filter(f=>f.saved).length+' saved · '+files.length+' images':'No images yet';
 for(const f of files){const button=document.createElement('button');button.className='queueItem'+(f.id===selected?' active':'')+(f.saved?' saved':'');button.title=f.name;const img=document.createElement('img');img.src=imageURL(f,'work',true);img.alt='';const text=document.createElement('div');text.className='qText';const name=document.createElement('strong');name.textContent=f.name;const dimensions=document.createElement('span');dimensions.className='originalDimensions';dimensions.textContent='Original: '+(f.original_size||[f.width,f.height]).join(' × ')+' px';text.append(name,dimensions);button.append(img,text);button.onclick=guarded(async()=>{await flush();selected=f.id;await refresh(true)});
  // The full card is a selection button; trash is a sibling with its own action.
  const status=document.createElement('em');status.textContent=f.saved?'Saved':f.mask_applied?'Cutout':f.mask?'Masking':f.pending_color||f.revision>1?'Editing':'Original';status.dataset.stage=status.textContent.toLowerCase();
  const trash=makeButton('remove-'+f.id,'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/></svg>','Remove '+f.name+' from batch');trash.className='portraitTrash';trash.setAttribute('data-mutation','');trash.disabled=busy;trash.onclick=guarded(async e=>{e.stopPropagation();await flush();const batchId=batch.id;await api('/api/remove-portrait',{batch:batchId,id:f.id});if(selected===f.id)selected=null;await refresh(true)});
  const statusRow=document.createElement('div');statusRow.className='portraitStatusRow';statusRow.append(status);button.append(statusRow);
  const row=document.createElement('div');row.className='portraitRow';row.dataset.portraitId=f.id;row.addEventListener('mouseenter',()=>hoveredPortraitId=f.id);row.addEventListener('mouseleave',()=>{if(hoveredPortraitId===f.id)hoveredPortraitId=null});row.append(button,trash);$('queue').append(row)}
 $('queue').scrollTop=queueScroll.top;$('queue').scrollLeft=queueScroll.left;
}
function renderOutput(){$('detectionProfile').value=app.settings.model;if(outputDraft&&outputDraft.batch!==batch?.id)outputDraft=null;const fs=batch?.files||[];$('saveScope').textContent=fs.filter(f=>f.mask).length+' cutouts · '+fs.filter(f=>!f.mask).length+' without masks stay in batch';if(document.activeElement!==$('finalFolder'))$('finalFolder').value=outputDraft?.folder??app.settings.final_folder??'';if(batch){if(document.activeElement!==$('subfolder'))$('subfolder').value=outputDraft?.subfolder??batch.subfolder;$('outputSize').textContent=`${batch.canvas.width} × ${batch.canvas.height} · PNG · ${batch.canvas.dpi} dpi`}}
async function loadSelected(){$('loupe').hidden=true;const sequence=++loadSequence,id=current.id;const [im,m,orig,review]=await Promise.all([loadImage(imageURL(current)),current.mask?loadImage(imageURL(current,'mask')):Promise.resolve(null),loadImage(imageURL(current,'first-original')),current.mask?loadImage(imageURL(current,'mask-review')):Promise.resolve(null)]);if(!current||current.id!==id||sequence!==loadSequence)return;workImg=im;reviewImg=review;maskImg=m;originalImg=orig;$('empty').hidden=true;$('filename').textContent=current.name;$('filename').title=current.name;$('filePosition').textContent=(batch.files.findIndex(f=>f.id===current.id)+1)+' / '+batch.files.length;$('sourceSize').textContent=`${current.width} × ${current.height}`;$('cutoutStatus').textContent=current.mask_applied?'Applied · editable':current.mask?'Preview only':'No mask yet';syncPosition();syncColor();updatePreview();loadComparison();if(current.photos_error)message(current.photos_error,true);else if(current.external_error)message(current.external_error,true);else if(current.alignment_note)message(current.alignment_note)}
function syncPosition(){const t=current.transform;$('scale').value=t.scale*100;$('scaleNumber').value=(t.scale*100).toFixed(1);for(const [field,key] of [['positionX','x'],['positionY','y']]){$(field).value=t[key];$(field+'Number').value=Math.round(t[key])}
 const scale=t.scale;$('resolutionHint').textContent=scale>1.05?`Current framing enlarges the source ${scale.toFixed(2)}×. Upscale before final output.`:'Source has enough pixels for this framing. Enhance only if needed.'}
function syncColor(){for(const k of ['hue','saturation','lightness','shadows','highlights','temperature','tint','exposure','grain']){$(k).value=draft[k]||0;$(k+'Out').textContent=draft[k]||0}$('colorStatus').textContent=isDraft()?'Preview · unapplied':'Applied';$('applyColor').disabled=!isDraft();drawCurves()}
function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
const RANGE_CENTERS={red:0,yellow:60,green:120,cyan:180,blue:240,magenta:300};
function adjustPixels(c,col){const ctx=c.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,c.width,c.height),a=im.data;const maps=['red','green','blue'].map(ch=>Array.from({length:256},(_,i)=>interp(interp(i/255,col[ch]),col.rgb)));
 const rangeEntries=Object.entries(col.color_ranges||{}).filter(([,v])=>v.hue||v.saturation||v.lightness);
 const exposure=col.exposure||0,lightness=col.lightness||0,grain=col.grain||0;
 for(let i=0;i<a.length;i+=4){let r=maps[0][a[i]],g=maps[1][a[i+1]],b=maps[2][a[i+2]];const temp=col.temperature||0,tint=col.tint||0,exp=1+exposure/100;r=Math.max(0,Math.min(1,r*(1+temp*.0015+tint*.0005)*exp));g=Math.max(0,Math.min(1,g*(1-tint*.001)*exp));b=Math.max(0,Math.min(1,b*(1-temp*.0015+tint*.0005)*exp));const lum=.2126*r+.7152*g+.0722*b;const d=col.shadows/100*.45*(1-lum)**3+col.highlights/100*.35*lum**3;r=Math.max(0,Math.min(1,r+d));g=Math.max(0,Math.min(1,g+d));b=Math.max(0,Math.min(1,b+d));
 if(col.hue||col.saturation||lightness||rangeEntries.length){const max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min;let h=0;if(delta)h=max===r?((g-b)/delta)%6:max===g?(b-r)/delta+2:(r-g)/delta+4;h=((h*60)%360+360)%360;
  let hh=((h+col.hue)%360+360)%360,sat=Math.max(0,Math.min(1,(max?delta/max:0)*(1+col.saturation/100))),v=Math.max(0,Math.min(1,max*(1+lightness/100)));
  for(const [name,entry] of rangeEntries){const center=entry.center??RANGE_CENTERS[name],d=((h-center+180)%360+360)%360-180;let weight;if(entry.bounds){const [a,b,c,z]=entry.bounds;weight=Math.max(0,Math.min(1,d>=b?1:(d-a)/Math.max(b-a,1e-6),d<=c?1:(z-d)/Math.max(z-c,1e-6)))}else weight=Math.max(0,1-Math.abs(d)/60);if(!weight)continue;hh=((hh+weight*entry.hue)%360+360)%360;sat=Math.max(0,Math.min(1,sat*(1+weight*entry.saturation/100)));v=Math.max(0,Math.min(1,v*(1+weight*entry.lightness/100)))}
  const C=v*sat,X=C*(1-Math.abs((hh/60)%2-1)),m=v-C;let q=hh<60?[C,X,0]:hh<120?[X,C,0]:hh<180?[0,C,X]:hh<240?[0,X,C]:hh<300?[X,0,C]:[C,0,X];[r,g,b]=q.map(x=>x+m)}
 if(grain){const n=(Math.random()-.5)*(grain/100*.08);r=Math.max(0,Math.min(1,r+n));g=Math.max(0,Math.min(1,g+n));b=Math.max(0,Math.min(1,b+n))}
 a[i]=Math.round(r*255);a[i+1]=Math.round(g*255);a[i+2]=Math.round(b*255)}ctx.putImageData(im,0,0);return c}
const colorWorker=new Worker('color-worker.js');let colorWaiting=null,colorNext=null,lastColorPresented=0,colorInteracting=false;
colorWorker.onmessage=({data:d})=>{const job=colorWaiting;colorWaiting=null;if(job&&d.id>lastColorPresented&&current?.id===job.file&&job.source===workImg){if(d.error)message('Color preview failed: '+d.error,true);else{job.canvas.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(d.pixels),job.canvas.width,job.canvas.height),0,0);if(d.reviewPixels){job.review.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(d.reviewPixels),job.review.width,job.review.height),0,0)}reviewPreview=job.review||null;lastColorPresented=d.id;preview=job.canvas;finishPreview()}}if(colorNext){const next=colorNext;colorNext=null;sendColor(next)}};
colorWorker.onerror=()=>{colorWaiting=null;colorNext=null;message('Color preview engine stopped. Reopen Clarette; applied edits are saved.',true)};
function sendColor(job){colorWaiting=job;const im=job.canvas.getContext('2d').getImageData(0,0,job.canvas.width,job.canvas.height),review=job.review?.getContext('2d').getImageData(0,0,job.review.width,job.review.height);const transfers=[im.data.buffer];if(review)transfers.push(review.data.buffer);colorWorker.postMessage({id:job.id,width:job.canvas.width,height:job.canvas.height,color:job.color,pixels:im.data.buffer,reviewPixels:review?.data.buffer},transfers)}
function updatePreview(){if(!workImg)return;const s=Math.min(1,colorInteracting?750/Math.max(workImg.naturalWidth,workImg.naturalHeight):Math.sqrt(8000000/(workImg.naturalWidth*workImg.naturalHeight)));const c=canvas(Math.round(workImg.naturalWidth*s),Math.round(workImg.naturalHeight*s));c.getContext('2d').drawImage(workImg,0,0,c.width,c.height);const job={id:++previewSequence,file:current.id,source:workImg,canvas:c,color:clone(app?.settings.preview_color===false?neutral():draft)};if(reviewImg){job.review=canvas(c.width,c.height);job.review.getContext('2d').drawImage(reviewImg,0,0,c.width,c.height)}if(app?.settings.preview_color===false||JSON.stringify(draft)===JSON.stringify(neutral())){colorNext=null;lastColorPresented=job.id;reviewPreview=job.review||null;preview=c;finishPreview();return}if(colorWaiting)colorNext=job;else sendColor(job);}
function finishPreview(){
 flushCompletionSounds();
 cutPreview=canvas(preview.width,preview.height);let cx=cutPreview.getContext('2d');cx.drawImage(preview,0,0);overlay=null;
 if(maskImg&&app.settings.masking_enabled!==false){const m=canvas(preview.width,preview.height);const mx=m.getContext('2d',{willReadFrequently:true});mx.drawImage(maskImg,0,0,m.width,m.height);let pixels=mx.getImageData(0,0,m.width,m.height);for(let i=0;i<pixels.data.length;i+=4){pixels.data[i+3]=pixels.data[i];pixels.data[i]=255;pixels.data[i+1]=255;pixels.data[i+2]=255}mx.putImageData(pixels,0,0);const cutPixels=cx.getImageData(0,0,preview.width,preview.height);for(let i=0;i<cutPixels.data.length;i+=4)cutPixels.data[i+3]=Math.min(cutPixels.data[i+3],pixels.data[i+3]);cx.putImageData(cutPixels,0,0);overlay=canvas(m.width,m.height);const ox=overlay.getContext('2d');ox.drawImage(m,0,0);ox.globalCompositeOperation='source-in';ox.fillStyle='rgba(255,43,59,.47)';ox.fillRect(0,0,m.width,m.height)}
 $('imageHint').textContent=maskImg?(current.mask_applied?'Cutout applied. You can still refine its mask.':'Red = keep. Review the edges, then Apply cutout.'):'Detect the subject to create an editable mask.';draw();drawCurves()}
function geometry(c){const w=c.clientWidth,h=c.clientHeight,C=batch.canvas;let k=$('viewZoom').value;k=k==='fit'||!k?Math.min((w-36)/C.width,(h-36)/C.height):k==='fill'?Math.max(w/C.width,h/C.height):Number(k);return {w,h,k,ox:(w-C.width*k)/2+viewShift.x,oy:(h-C.height*k)/2+viewShift.y}}
const checkerTile=canvas(32,32);{const c=checkerTile.getContext('2d');c.fillStyle='#252831';c.fillRect(0,0,32,32);c.fillStyle='#30343e';c.fillRect(16,0,16,16);c.fillRect(0,16,16,16)}
function checkers(ctx,w,h){ctx.fillStyle=ctx.createPattern(checkerTile,'repeat');ctx.fillRect(0,0,w,h)}
function drawOne(c,isCutout){const dpr=Math.min(window.devicePixelRatio||1,2),w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#12141a';ctx.fillRect(0,0,w,h);if(!preview||!current||!batch)return;
 const g=geometry(c),t=current.transform,x=g.ox+t.x*g.k,y=g.oy+t.y*g.k,iw=current.width*t.scale*g.k,ih=current.height*t.scale*g.k;
 ctx.save();ctx.beginPath();ctx.rect(g.ox,g.oy,batch.canvas.width*g.k,batch.canvas.height*g.k);ctx.clip();checkers(ctx,w,h);ctx.save();ctx.translate(x+iw/2,y+ih/2);ctx.rotate((t.rotation||0)*Math.PI/180);ctx.translate(-x-iw/2,-y-ih/2);let im=before?originalImg:(isCutout?cutPreview:(cutoutVisible?cutPreview:(reviewPreview||preview)));if(mode==='compare'&&!before){im=isCutout?(comparisonKind==='enhancement'?preview:cutPreview):(comparisonKind==='refinement'?comparisonImg:originalImg)||originalImg;}if(before){const region=(current.baseline===current.original?current.original_region:null)||[0,0,originalImg.naturalWidth,originalImg.naturalHeight];ctx.drawImage(im,...region,x,y,iw,ih)}else ctx.drawImage(im,x,y,iw,ih);
 if(!before&&!cutoutVisible&&mode==='mask'&&!isCutout&&overlay)ctx.drawImage(overlay,x,y,iw,ih);
 if(stroke&&!isCutout){ctx.strokeStyle=stroke.mode==='keep'?'#ff6479':stroke.mode==='remove'?'#70c9ff':'#f2d181';ctx.lineWidth=stroke.shape==='polygon'?1.5:stroke.size*t.scale*g.k;ctx.lineCap='round';ctx.lineJoin='round';ctx.globalAlpha=.65;ctx.beginPath();stroke.points.forEach((p,i)=>{const xx=x+p[0]*iw,yy=y+p[1]*ih;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});if(stroke.shape==='polygon'){ctx.closePath();ctx.fillStyle=ctx.strokeStyle;ctx.globalAlpha=.15;ctx.fill();ctx.globalAlpha=1;ctx.setLineDash([5,4])}ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1}
 ctx.restore();ctx.restore();ctx.strokeStyle='#b5a7cb';ctx.lineWidth=1.5;ctx.strokeRect(g.ox,g.oy,batch.canvas.width*g.k,batch.canvas.height*g.k);
 if($('guide').checked||guideEditing)drawGuide(ctx,g,w,h);
}
function draw(){updateBrushCursor();drawOne($('mainCanvas'),false);if(mode==='compare')drawOne($('cutoutCanvas'),true)}
function setMode(m){if(m==='compare'&&mode!=='compare'&&$('viewZoom').value==='fill')$('viewZoom').value='fit';mode=m;$('before').hidden=false;if(m==='compare')before=false;for(const b of $('views').children){b.classList.toggle('active',b.dataset.view===m);b.setAttribute('aria-selected',String(b.dataset.view===m))}moveTabGlow();$('previews').classList.toggle('compare',m==='compare');$('cutoutPane').hidden=m!=='compare';$('maskLegend').hidden=m==='image';$('leftTitle').textContent=m==='image'?'Preview':m==='mask'?'Masking':comparisonKind==='refinement'?'Before refinement':'Original';$('rightTitle').textContent=comparisonKind==='enhancement'?'Enhanced':comparisonKind==='refinement'?'After refinement':'Cutout result';$('compareKind').hidden=m!=='compare';$('cutoutStatus').textContent=m==='compare'&&comparisonKind==='enhancement'?'Working detail':current?.mask_applied?'Applied · editable':current?.mask?'Preview only':'No mask yet';$('maskLegend').hidden=m!=='mask';requestAnimationFrame(draw)}
function sourcePoint(e){const c=$('mainCanvas'),r=c.getBoundingClientRect(),g=geometry(c),t=current.transform;return [(e.clientX-r.left-g.ox-t.x*g.k)/(current.width*t.scale*g.k),(e.clientY-r.top-g.oy-t.y*g.k)/(current.height*t.scale*g.k)]}
function drawLoupe(p){if(!$('loupeToggle').checked||!current||!workImg){$('loupe').hidden=true;return}$('loupe').hidden=false;const c=$('loupeCanvas'),cx=c.getContext('2d'),sz=(c.clientWidth||160)/3;const crop=canvas(Math.ceil(sz),Math.ceil(sz));crop.getContext('2d').drawImage(reviewImg||workImg,p[0]*current.width-sz/2,p[1]*current.height-sz/2,sz,sz,0,0,crop.width,crop.height);adjustPixels(crop,draft);cx.imageSmoothingEnabled=false;cx.clearRect(0,0,c.width,c.height);cx.drawImage(crop,0,0,c.width,c.height);
 if(maskImg&&mode!=='image'){const m=canvas(c.width,c.height),mx=m.getContext('2d',{willReadFrequently:true});mx.drawImage(maskImg,p[0]*current.width-sz/2,p[1]*current.height-sz/2,sz,sz,0,0,c.width,c.height);const a=mx.getImageData(0,0,c.width,c.height);for(let i=0;i<a.data.length;i+=4){a.data[i+3]=a.data[i]*.47;a.data[i]=255;a.data[i+1]=43;a.data[i+2]=59}mx.putImageData(a,0,0);cx.drawImage(m,0,0)}}
$('mainCanvas').onpointerdown=e=>{if(!current||(busy&&e.button!==1))return;$('mainCanvas').setPointerCapture(e.pointerId);const p=sourcePoint(e);if(e.button===1){drag={inspect:true,x:e.clientX,y:e.clientY,shift:{...viewShift}};return}if(e.button!==0)return;if(brush==='move'&&current.position_locked)return;if(brush==='move'){drag={x:e.clientX,y:e.clientY,t:clone(current.transform)};return}if(p.some(v=>v<0||v>1))return;setMode('mask');stroke={mode:brush==='lasso'?$('lassoMode').value:brush,shape:brush==='lasso'?'polygon':'brush',hardness:Number($('brushHardness').value),feather:Number($('lassoFeather').value),size:Number($('brushSize').value),points:[p]};draw()};
$('mainCanvas').onpointermove=e=>{brushPointer={x:e.clientX,y:e.clientY};updateBrushCursor();if(!current)return;const p=sourcePoint(e);drawLoupe(p);if(busy&&!drag?.inspect)return;if(drag){if(drag.inspect){viewShift={x:drag.shift.x+e.clientX-drag.x,y:drag.shift.y+e.clientY-drag.y}}else{const g=geometry($('mainCanvas'));current.transform={...drag.t,x:drag.t.x+(e.clientX-drag.x)/g.k,y:drag.t.y+(e.clientY-drag.y)/g.k};syncPosition()}draw()}else if(stroke){stroke.points.push(p.map(v=>Math.min(1,Math.max(0,v))));draw()}};
$('mainCanvas').onpointerup=guarded(async()=>{if(drag){if(!drag.inspect)schedule();drag=null;return}if(stroke){const s=stroke;if(s.points.length===1)s.points.push(s.points[0]);stroke=null;await flush();await api('/api/mask-paint',context({strokes:[s]}));await refresh();draw()}});
$('mainCanvas').onpointercancel=()=>{stroke=null;drag=null;draw()};$('mainCanvas').onpointerleave=()=>{brushPointer=null;updateBrushCursor()};legacyShortcut('wheel',e=>{if(!current)return;e.preventDefault();const c=$('mainCanvas'),rect=c.getBoundingClientRect(),g=geometry(c);const factor=Math.exp(-Math.max(-120,Math.min(120,e.deltaY))*.0025);
if(current.position_locked){setInspectionZoom(g.k*factor,{x:e.clientX-rect.left,y:e.clientY-rect.top});return}
if(busy||stroke||drag||guideEditing)return;
const t=current.transform,px=(e.clientX-rect.left-g.ox)/g.k,py=(e.clientY-rect.top-g.oy)/g.k,scale=Math.max(.001,Math.min(100,t.scale*factor)),ratio=scale/t.scale;
current.transform={scale,x:px-(px-t.x)*ratio,y:py-(py-t.y)*ratio};syncPosition();draw();syncWorkflow();schedule();},{passive:false});
for(const b of $('views').children)b.onclick=()=>setMode(b.dataset.view);for(const b of $('brushTools').children)b.onclick=()=>{brush=b.dataset.brush;for(const x of $('brushTools').children)x.classList.toggle('active',x===b);updateBrushCursor();if(brush!=='move')setMode('mask')};$('brushSize').oninput=()=>{$('brushSizeOut').textContent=$('brushSize').value;updateBrushCursor()};$('guide').onchange=draw;$('viewZoom').onchange=()=>{viewShift={x:0,y:0};draw()};$('before').onclick=()=>{before=!before;$('before').classList.toggle('active',before);$('before').textContent=before?'Showing original':'Before / After';draw()};$('loupeToggle').onchange=()=>{if(!$('loupeToggle').checked)$('loupe').hidden=true};
for(const [id,key] of [['scale','scale'],['positionX','x'],['positionY','y']])for(const suffix of ['', 'Number'])$(id+suffix).oninput=()=>{if(!current)return;const n=Number($(id+suffix).value);if(!Number.isFinite(n)||(key==='scale'&&n<=0))return;current.transform[key]=key==='scale'?n/100:n;syncPosition();draw();schedule()};
$('resetPosition').onclick=()=>{if(!current||current.position_locked)return;const c=batch.canvas,s=Math.min(c.width/current.width,c.height/current.height);current.transform={scale:s,x:(c.width-current.width*s)/2,y:(c.height-current.height*s)/2};syncPosition();draw();schedule()};
function drawCurves(){const c=$('curves'),cx=c.getContext('2d'),w=c.width,h=c.height;cx.clearRect(0,0,w,h);cx.fillStyle='#191b22';cx.fillRect(0,0,w,h);cx.strokeStyle='#2c3d4b';cx.lineWidth=1;for(let i=0;i<5;i++){cx.beginPath();cx.moveTo(i*w/4,0);cx.lineTo(i*w/4,h);cx.moveTo(0,i*h/4);cx.lineTo(w,i*h/4);cx.stroke()}
 if(preview){const sc=canvas(100,100);const sx=sc.getContext('2d',{willReadFrequently:true});sx.drawImage(preview,0,0,100,100);const a=sx.getImageData(0,0,100,100).data,hist=new Array(64).fill(0);for(let i=0;i<a.length;i+=4)hist[Math.min(63,Math.floor((a[i]+a[i+1]+a[i+2])/12))]++;const max=Math.max(...hist);cx.fillStyle='#6b7d8f45';hist.forEach((v,i)=>cx.fillRect(i*w/64,h-v/max*h*.75,w/64,v/max*h*.75))}
 const channel=$('curveChannel').value,source=draft||neutral();
 const drawLine=(points,color,width)=>{cx.strokeStyle=color;cx.lineWidth=width;cx.beginPath();for(let i=0;i<=256;i++){const x=i/256,y=interp(x,points);i?cx.lineTo(x*w,(1-y)*h):cx.moveTo(x*w,(1-y)*h)}cx.stroke()};
 // RGB shows Red/Green/Blue as subdued (thinner, translucent) reference
 // lines behind the editable master curve -- lets you see whether any
 // channel has its own edits without leaving RGB mode, but they're each
 // still only *editable* from their own R/G/B selection: curveDrag and the
 // point list a click/drag operates on always come from draft[channel],
 // the currently-selected one, regardless of what's drawn on screen.
 if(channel==='rgb'){cx.globalAlpha=.55;drawLine(source.red,'#f7888d',1.3);drawLine(source.green,'#7bdbac',1.3);drawLine(source.blue,'#69b5fd',1.3);cx.globalAlpha=1}
 const pts=source[channel];drawLine(pts,{rgb:'#dceaff',red:'#f7888d',green:'#7bdbac',blue:'#69b5fd'}[channel],2);cx.fillStyle='#eaf3ff';for(const [x,y] of pts){cx.beginPath();cx.arc(x*w,(1-y)*h,3.5,0,Math.PI*2);cx.fill()}}
function curvePoint(e){const r=$('curves').getBoundingClientRect();return [Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),Math.min(1,Math.max(0,1-(e.clientY-r.top)/r.height))]}
$('curves').onpointerdown=e=>{if(!current)return;const p=curvePoint(e),pts=draft[$('curveChannel').value];let nearest=pts.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<.06);if(nearest<0&&(p[0]<.005||p[0]>.995)){nearest=p[0]<.005?0:pts.length-1}if(nearest<0&&pts.length<20){if(pts.some(q=>Math.abs(q[0]-p[0])<.005))return;pts.push(p);pts.sort((a,b)=>a[0]-b[0]);nearest=pts.indexOf(p)}curveDrag=nearest;$('curves').setPointerCapture(e.pointerId);drawCurves();queueLiveColor()};$('curves').onpointermove=e=>{if(curveDrag<0)return;const pts=draft[$('curveChannel').value],p=curvePoint(e);p[0]=curveDrag===0?0:curveDrag===pts.length-1?1:Math.min(pts[curveDrag+1][0]-.005,Math.max(pts[curveDrag-1][0]+.005,p[0]));pts[curveDrag]=p;drawCurves();queueLiveColor()};$('curves').onpointerup=()=>{curveDrag=-1;colorInteracting=false;if(current){syncColor();updatePreview();schedule()}};$('curves').ondblclick=e=>{if(!current)return;const p=curvePoint(e),pts=draft[$('curveChannel').value],i=pts.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<.07);if(i>0&&i<pts.length-1){pts.splice(i,1);syncColor();updatePreview();schedule()}};$('curveChannel').onchange=drawCurves;
let colorTimer;for(const k of ['hue','saturation','shadows','highlights','temperature','tint'])$(k).oninput=()=>{if(!current)return;draft[k]=Number($(k).value);syncColor();queueLiveColor();schedule()};
$('applyColor').onclick=guarded(async()=>{await flush();await api('/api/color-apply',context({color:draft}));await refresh(true);message('Color applied. Mask and original preserved.')});$('resetColor').onclick=()=>{if(!current)return;draft=clone(current.color);syncColor();updatePreview();schedule()};$('neutralColor').onclick=()=>{if(!current)return;draft=neutral();syncColor();updatePreview();schedule()};$('autoColor').onclick=guarded(()=>run('/api/color-auto'));
async function run(path,extra={}){await flush();if(['/api/enhance','/api/refine-edges','/api/cloud-enhance'].includes(path)&&isDraft()){if(!confirm('Apply your pending color edits before processing?'))return;await api('/api/color-apply',context({color:draft}));await refresh(true);}await api(path,context(extra));await refresh()}
$('autoFit').onclick=guarded(async()=>{await run('/api/detect');$('fitStatus').textContent='Running the YuNet face detector…'});$('detectMask').onclick=guarded(async()=>{if(current.mask&&!confirm('Replace the current mask? You can Undo this change.'))return;await run('/api/mask-detect');setMode('mask')});$('applyMask').onclick=guarded(async()=>{await run('/api/mask-apply');await refresh(true);message('Cutout applied. Save finals when ready.')});$('undo').onclick=guarded(async()=>{await run('/api/undo');await refresh(true)});
$('enhance').onclick=guarded(async()=>{let scale=$('upscale').value;if(scale==='auto')scale=current.transform.scale>2.05?4:current.transform.scale>1.05?2:1;if(Number(scale)>1&&current.mask&&!confirm('Upscaling changes the source dimensions and resets the mask. Continue?'))return;await run('/api/enhance',{scale:Number(scale),amount:Number($('detailAmount').value)})});
function headDraw(){const c=$('headCanvas'),cx=c.getContext('2d');cx.drawImage(workImg,0,0,c.width,c.height);if(headRect){cx.strokeStyle='#bda1ed';cx.lineWidth=2;cx.setLineDash([7,5]);cx.strokeRect(headRect.x*c.width,headRect.y*c.height,headRect.w*c.width,headRect.h*c.height);cx.setLineDash([])}}
$('headBox').onclick=guarded(async()=>{if(!current)return;await flush();const c=$('headCanvas'),s=Math.min(1,520/current.width,390/current.height);c.width=Math.round(current.width*s);c.height=Math.round(current.height*s);const face=current.crop_suggestion?.face;headRect=face?{x:face.x/current.width,y:face.y/current.height,w:face.w/current.width,h:face.h/current.height}:null;$('useHead').disabled=!headRect;$('headDialog').showModal();headDraw()});function hp(e){const r=$('headCanvas').getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
$('headCanvas').onpointerdown=e=>{headStart=hp(e);$('headCanvas').setPointerCapture(e.pointerId)};$('headCanvas').onpointermove=e=>{if(!headStart)return;const p=hp(e);headRect={x:Math.min(p.x,headStart.x),y:Math.min(p.y,headStart.y),w:Math.abs(p.x-headStart.x),h:Math.abs(p.y-headStart.y)};headDraw()};$('headCanvas').onpointerup=()=>{headStart=null;$('useHead').disabled=!headRect||headRect.w<.01||headRect.h<.01};$('useHead').onclick=()=>{const c=batch.canvas,r=headRect,hw=c.width*c.headW,s=Math.min(hw/(r.w*current.width),hw*1.18/(r.h*current.height));current.transform={scale:s,x:c.width/2-(r.x+r.w/2)*current.width*s,y:c.height*c.headTop-r.y*current.height*s};$('headDialog').close();syncPosition();draw();schedule();message('Head Box applied. Drag to fine-tune.')};
function show(id){$(id).showModal()}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('help').onclick=()=>openNative('help');$('settings').onclick=()=>{$('prompt').value=localStorage.getItem('glass-prompt')||app.prompt;$('maskModel').value=app.settings.model;$('notifications').checked=app.settings.notifications;$('accelerate').checked=!!app.settings.accelerate;$('autoGuide').checked=app.settings.auto_guide!==false;show('settingsDialog')};$('savePrompt').onclick=()=>{localStorage.setItem('glass-prompt',$('prompt').value);message('Enhancement prompt saved')};$('maskModel').onchange=guarded(async()=>{await api('/api/settings',{model:$('maskModel').value});await refresh()});$('notifications').onchange=guarded(async()=>{await api('/api/settings',{notifications:$('notifications').checked});await refresh()});
function unfinished(){return Object.values(app?.batches||{}).some(b=>b.files.some(f=>!f.saved))||isDraft()||editPending}
window.addEventListener('beforeunload',e=>{if(!app?.native&&(busy||editPending)){e.preventDefault();e.returnValue=''}});$('quit').onclick=guarded(async()=>{if(!busy)await Promise.race([flush(),new Promise(resolve=>setTimeout(resolve,500))]);if(!app.native&&(busy||unfinished())&&!confirm('Some images are unfinished. Your session is saved. Quit anyway?'))return;await api('/api/quit');message('Clarette closed. You can close this window.')});
async function handoff(service){await flush();const p=localStorage.getItem('glass-prompt')||app.prompt;let copied=false;try{await navigator.clipboard.writeText(p);copied=true}catch{}await api('/api/open',context({service}));try{await api('/api/open',context({service:'working'}))}catch{}if(!copied){$('resultTitle').textContent='Copy your enhancement prompt';$('resultText').textContent=p;show('resultDialog')}else message('Prompt copied. Drag the Working image into '+(service==='chatgpt'?'ChatGPT':'Gemini')+' and paste.')}
$('chatgpt').onclick=guarded(()=>handoff('chatgpt'));$('gemini').onclick=guarded(()=>handoff('gemini'));$('working').onclick=guarded(()=>api('/api/open',context({service:'working'})));$('photoshop').onclick=guarded(async()=>{await flush();await api('/api/open',context({service:'photoshop'}))});$('openFinal').onclick=guarded(()=>api('/api/open',{service:'final'}));
const readBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
function chooseImport(append){appendImport=append;$('fileInput').click()}$('importBtn').onclick=()=>chooseImport(true);$('emptyImport').onclick=()=>chooseImport(false);$('newBatch').onclick=()=>chooseImport(false);$('fileInput').onchange=guarded(async e=>{const files=[...e.target.files];if(!files.length)return;await flush();if(files.reduce((s,f)=>s+f.size,0)>100000000)throw Error('Import fewer than 100 MB at a time.');const payload=await Promise.all(files.map(async f=>({name:f.name,data:await readBase64(f)})));const result=await api('/api/import',{files:payload,append:appendImport,name:files.length===1&&files[0].name.endsWith('.zip')?files[0].name.slice(0,-4):undefined});e.target.value='';selected=null;await refresh(true);message('Imported '+result.added+' images'+(result.skipped.length?' · '+result.skipped.length+' skipped':''));if(result.skipped.length){$('resultTitle').textContent='Import details';$('resultText').textContent=result.skipped.join('\n');show('resultDialog')}});
$('replaceWorking').onclick=()=>{if(current)$('replaceInput').click()};$('replaceInput').onchange=guarded(async e=>{const file=e.target.files[0];if(!file)return;if(!confirm('Replace the Working source with this enhanced image? The current mask resets; Undo is available.'))return;await flush();await api('/api/replace',context({data:await readBase64(file)}));e.target.value='';await refresh(true);message('Enhanced image imported. Framing retained; review it before cutting out.')});$('resetSource').onclick=guarded(async()=>{if(!confirm('Restore this image from its untouched original?'))return;await run('/api/reset-source');await refresh(true)});
$('batchSelect').onchange=guarded(async()=>{await flush();await api('/api/select-batch',{batch:$('batchSelect').value});selected=null;await refresh(true)});
for(const id of ['finalFolder','subfolder'])$(id).oninput=()=>{outputDraft={batch:batch?.id,folder:$('finalFolder').value,subfolder:$('subfolder').value}};
$('chooseFolder').onclick=guarded(async()=>{const d=await api('/api/choose-folder');if(!d.cancelled){$('finalFolder').value=d.path;if(outputDraft)outputDraft.folder=d.path;await refresh()}});$('finalFolder').onchange=guarded(async()=>{await api('/api/settings',{final_folder:$('finalFolder').value});await refresh()});$('subfolder').onchange=guarded(async()=>{await api('/api/output',{subfolder:$('subfolder').value});await refresh()});
async function exportBatch(applyAll=false){
 const output={folder:$('finalFolder').value,subfolder:$('subfolder').value};await flush();await api('/api/settings',{final_folder:output.folder});await api('/api/output',{subfolder:output.subfolder});
 const folderMode=await resolveDestination();if(!folderMode)return;
 await api('/api/export',{overwrite:$('overwrite').checked,apply_all:applyAll,folder_mode:folderMode});$('saveEditsDialog').close();await refresh();
}
$('saveFinals').onclick=guarded(async()=>{await flush();if(!batch?.files.length)throw Error('Import images first');const plan=await api('/api/export-plan');if(!plan.eligible)throw Error('No cutouts to save yet. Detect or paint a subject mask first.');if(plan.pending){$('pendingSummary').textContent=plan.pending+' image(s) have unapplied edits. '+plan.eligible+' cutout(s) will be saved; '+plan.missing.length+' image(s) without masks will stay in the batch.';show('saveEditsDialog')}else await exportBatch()});
$('applyAllSave').onclick=guarded(()=>exportBatch(true));
$('clearSaved').onclick=guarded(async()=>{await flush();if(!confirm('Remove temporary copies of verified saved images? Final exports and unfinished images will stay.'))return;const d=await api('/api/clear-saved');selected=null;await refresh(true);message(d.removed.length+' saved images cleared; '+d.retained.length+' unfinished or changed images kept.')});
function presetFields(c){$('canvasWidth').value=c.width;$('canvasHeight').value=c.height;$('dpi').value=c.dpi;$('headWidth').value=Number((c.headW*100).toFixed(2));$('headTop').value=Number((c.headTop*100).toFixed(2))}
$('presets').onclick=()=>{if(!batch){message('Import a batch first');return}$('presetSelect').replaceChildren();$('presetSelect').add(new Option('Custom','custom'));for(const [id,p] of Object.entries(app.presets))$('presetSelect').add(new Option(p.label,id));presetFields(batch.canvas);show('presetDialog')};$('presetSelect').onchange=()=>{if($('presetSelect').value!=='custom')presetFields(app.presets[$('presetSelect').value])};for(const id of ['canvasWidth','canvasHeight','dpi','headWidth','headTop'])$(id).addEventListener('input',()=>{$('presetSelect').value='custom'});async function applyPreset(){await flush();const c={width:+$('canvasWidth').value,height:+$('canvasHeight').value,dpi:+$('dpi').value,headW:+$('headWidth').value/100,headTop:+$('headTop').value/100,label:$('presetSelect').selectedOptions[0]?.textContent||'Custom',preset_id:$('presetSelect').value};await api('/api/output',{canvas:c});await refresh(true)}$('applyPreset').onclick=guarded(async()=>{await applyPreset();$('presetDialog').close()});$('savePreset').onclick=guarded(async()=>{const label=prompt('Name this custom preset:');if(!label)return;await applyPreset();await api('/api/preset',{label});await refresh();message('Preset saved');$('presetDialog').close()});
// Completion audio is acknowledged only after the result and notification paint.
const completionSounds=new Set();let completionFramePending=false;
function flushCompletionSounds(){
 if(!completionSounds.size||completionFramePending||document.visibilityState!=='visible'||colorWaiting||colorNext)return;
 completionFramePending=true;
 requestAnimationFrame(()=>requestAnimationFrame(()=>{
  completionFramePending=false;
  if(document.visibilityState!=='visible'||colorWaiting||colorNext)return;
  for(const id of [...completionSounds]){
   completionSounds.delete(id);
   api('/api/job-presented',{job:id}).catch(()=>completionSounds.add(id));
  }
 }));
}
document.addEventListener('visibilitychange',flushCompletionSounds);
function renderJobs(){const jobs=app.jobs||[],active=jobs.find(j=>j.status==='running');busy=!!active;document.body.classList.toggle('busy',busy);$('jobbar').hidden=!busy;if(active){$('jobTitle').textContent=active.title;$('jobMessage').textContent=active.message+' · '+Math.floor(Date.now()/1000-active.started)+'s';$('cancelJob').disabled=active.cancel_requested;$('cancelJob').textContent=active.cancel_requested?'Stopping…':'Cancel';}document.querySelectorAll('[data-mutation]').forEach(el=>{el.disabled=busy||(el.id==='applyColor'&&!isDraft())||(el.id==='undo'&&!current?.can_undo)||(el.id==='redo'&&!current?.can_redo)});$('processingGlow').hidden=!busy; 
 for(const j of jobs){if(j.status==='running'||displayedJobs.has(j.id))continue;displayedJobs.add(j.id);if(j.status==='done'||j.status==='error')completionSounds.add(j.id);if(j.status==='cancelled'){message(j.message)}else if(j.status==='error'){message(j.title+': '+j.message,true);$('fitStatus').textContent=j.title==='Auto Fit'?j.message:$('fitStatus').textContent}else if(j.title==='Export batch'){const r=j.result;$('resultTitle').textContent='Batch export complete';$('resultText').textContent=`Saved: ${r.saved.length}\nNeeds attention: ${r.errors.length}`+(r.errors.length?'\n\n'+r.errors.join('\n'):'');show('resultDialog')}else{if(j.title==='Apply to All'){ $('resultTitle').textContent='Batch processing complete';$('resultText').textContent=(j.result.completed||[]).length+' portraits completed'+((j.result.errors||[]).length?'\n\n'+j.result.errors.join('\n'):'');show('resultDialog');}message(j.title+' complete');if(j.title==='Suggest headshot')$('fitStatus').textContent='Red guide suggested from face position. Head Box lets you adjust hair and hats.';if(j.title==='Auto Fit')$('fitStatus').textContent='Face detected. Check hair and hat against the guide.'}}
}
let brushPointer=null;
function updateBrushCursor(){const el=$('brushCursor');if(!brushPointer||!current||busy||!['keep','remove','refine'].includes(brush)){el.hidden=true;return}const r=$('mainCanvas').getBoundingClientRect(),g=geometry($('mainCanvas'));const size=Number($('brushSize').value)*current.transform.scale*g.k;el.hidden=false;el.style.width=el.style.height=size+'px';el.style.left=(brushPointer.x-r.left)+'px';el.style.top=(brushPointer.y-r.top)+'px';el.dataset.mode=brush;}
$('detailAmount').oninput=()=>$('detailAmountOut').textContent=$('detailAmount').value;
$('copyPrompt').onclick=guarded(async()=>{const text=localStorage.getItem('glass-prompt')||app?.prompt;if(!text)throw Error('Wait for the app to load');try{await navigator.clipboard.writeText(text)}catch{const field=document.createElement('textarea');field.value=text;document.body.append(field);field.select();const copied=document.execCommand('copy');field.remove();if(!copied)throw Error('Clipboard unavailable. Open Settings to copy the prompt manually.')}message('Enhancement prompt copied')});
$('accelerate').onchange=guarded(async()=>{await api('/api/settings',{accelerate:$('accelerate').checked});await refresh()});
$('applyCutouts').onclick=guarded(async()=>{await flush();if(!confirm('Apply every existing mask in this batch? Missing masks will not be detected.'))return;const r=await api('/api/apply-cutouts');await refresh(true);message(r.applied+' cutouts applied. Save batch finals exports all prepared cutouts.')});
$('edgeOptions').onclick=()=>{if(!current?.mask){message('Detect or paint a subject mask first',true);return}show('edgesDialog')};
$('runEdges').onclick=guarded(async()=>{await run('/api/refine-edges',{radius:Number($('edgeRadius').value),decontaminate:$('edgeColors').checked});$('edgesDialog').close()});
legacyShortcut('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;if(e.key==='['||e.key===']'){e.preventDefault();$('brushSize').value=Math.max(2,Math.min(200,Number($('brushSize').value)+(e.key===']'?5:-5)));$('brushSize').oninput()}});

$('detectionProfile').onchange=guarded(async()=>{await api('/api/settings',{model:$('detectionProfile').value});await refresh()});
$('autoGuide').onchange=guarded(async()=>{await api('/api/settings',{auto_guide:$('autoGuide').checked});await refresh()});
$('apiKeys').onclick=()=>show('apiDialog');

$('cancelJob').onclick=guarded(async()=>{const job=app.jobs.find(j=>j.status==='running');if(job){await api('/api/cancel',{job:job.id});await refresh()}});
$('suggestCrop').onclick=guarded(()=>run('/api/crop-suggest'));
async function loadComparison(){comparisonKind=$('compareKind').value;if((comparisonKind==='refinement'&&!current?.comparisons?.refinement)||(comparisonKind==='enhancement'&&!current?.comparisons?.enhancement)){$('compareKind').value='mask';comparisonKind='mask'}const id=current?.id,kind=comparisonKind;comparisonImg=null;if(kind==='refinement'&&current?.comparisons?.refinement){const im=await loadImage(imageURL(current,'refinement'));if(current?.id===id&&comparisonKind===kind)comparisonImg=im;}if(mode==='compare')setMode('compare')}
$('compareKind').onchange=guarded(async()=>{if($('compareKind').value==='refinement'&&!current?.comparisons?.refinement){message('Refine or brush an existing mask to create a Before refinement snapshot.');$('compareKind').value='mask'}if($('compareKind').value==='enhancement'&&!current?.comparisons?.enhancement){message('Enhance this image first to compare it with the original.');$('compareKind').value='mask'}await loadComparison()});
const mutationIds=['batchSelect','importBtn','emptyImport','newBatch','applyCutouts','autoFit','headBox','suggestCrop','resetPosition','scale','scaleNumber','positionX','positionXNumber','positionY','positionYNumber','hue','saturation','shadows','highlights','applyColor','resetColor','neutralColor','autoColor','detectMask','applyMask','undo','edgeOptions','enhance','replaceWorking','resetSource','saveFinals','clearSaved','finalFolder','subfolder','chooseFolder','presets','maskModel','detectionProfile','autoGuide','accelerate','notifications'];
for(const id of mutationIds)$(id).setAttribute('data-mutation','');

new ResizeObserver(draw).observe($('previews'));window.addEventListener('resize',draw);setInterval(async()=>{if(polling||editPending||drag||stroke)return;polling=true;try{await refresh()}catch(e){$('sessionStatus').textContent='Connection interrupted · reopen Clarette if it persists'}finally{polling=false}},1500);
drawCurves();refresh(true).catch(e=>message(e.message,true));

function moveTabGlow(){const bar=$('views'),tab=bar.querySelector('.active');if(!tab)return;bar.style.setProperty('--tab-x',tab.offsetLeft+'px');bar.style.setProperty('--tab-width',tab.offsetWidth+'px')}
$('views').setAttribute('role','tablist');for(const b of $('views').children)b.setAttribute('role','tab');
new ResizeObserver(moveTabGlow).observe($('views'));moveTabGlow();
