let cutoutVisible=false;
function originalHeld(value){before=value;$('before').classList.toggle('active',value);$('before').setAttribute('aria-pressed',String(value));draw()}
$('before').onclick=null;window.addEventListener('blur',()=>originalHeld(false));
$('before').onpointerdown=e=>{e.preventDefault();$('before').setPointerCapture(e.pointerId);originalHeld(true)};
for(const event of ['pointerup','pointercancel','lostpointercapture','blur'])$('before').addEventListener(event,()=>originalHeld(false));
$('before').onkeydown=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();originalHeld(true)}};
$('before').onkeyup=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();originalHeld(false)}};
window.addEventListener('blur',()=>originalHeld(false));
$('cutoutToggle').onclick=()=>{cutoutVisible=!cutoutVisible;$('cutoutToggle').setAttribute('aria-pressed',String(cutoutVisible));$('cutoutToggle').classList.toggle('active',cutoutVisible);draw()};
$('clearPortraits').setAttribute('data-mutation','');$('crop').setAttribute('data-mutation','');
$('clearPortraits').onclick=guarded(async()=>{if(!batch||(!batch.files.length&&!batch.removed_files?.length))return;await flush();const unsaved=batch.files.some(f=>!f.saved);if(unsaved&&!confirm('Clear all portraits from this batch? Some have not been exported. Original files and existing exports will be kept.'))return;await api('/api/clear-batch',{confirm_unsaved:unsaved});selected=null;await refresh(true)});
$('enhanceDrop').onclick=()=>$('replaceWorking').click();
$('enhanceDrop').ondragover=e=>{e.preventDefault();$('enhanceDrop').classList.add('dragover')};$('enhanceDrop').ondragleave=()=>$('enhanceDrop').classList.remove('dragover');
$('enhanceDrop').ondrop=guarded(async e=>{e.preventDefault();$('enhanceDrop').classList.remove('dragover');if(busy)return;const file=e.dataTransfer.files[0];if(!file)return;if(!current)throw Error('Add and select a portrait first');if(!confirm('Replace the selected portrait with this enhanced image? Its mask resets; Undo is available.'))return;await flush();await api('/api/replace',context({data:await readBase64(file)}));await refresh(true)});
for(const name of ['openai','gemini']){
 $(name+'Save').onclick=guarded(async()=>{const key=$(name+'Key').value;try{await api('/api/credentials',{provider:name,key});await api('/api/settings',{[name+'_model']:$(name+'Model').value});await refresh();$(name+'Status').textContent='Key saved';message('Key stored in macOS Keychain')}finally{$(name+'Key').value=''}});
 $(name+'Remove').onclick=guarded(async()=>{await api('/api/credentials',{provider:name,remove:true});await refresh();$(name+'Status').textContent='Not connected'});
 $(name+'Test').onclick=guarded(async()=>{$(name+'Status').textContent='Testing…';try{await api('/api/test-connection',{provider:name});$(name+'Status').textContent='Connected'}catch(e){$(name+'Status').textContent='Connection failed';throw e}});
 $(name+'Model').onchange=guarded(()=>api('/api/settings',{[name+'_model']:$(name+'Model').value}));
}
const openSettings=$('settings').onclick;$('settings').onclick=()=>{openSettings();for(const name of ['openai','gemini']){$(name+'Key').value='';$(name+'Status').textContent=app.settings[name+'_connected']?'Key saved':'Not connected';$(name+'Model').value=app.settings[name+'_model']||(name==='openai'?'gpt-image-1':'gemini-3.1-flash-image')}};
$('settingsDialog').addEventListener('close',()=>{for(const n of ['openai','gemini'])$(n+'Key').value=''});
const localEnhance=$('enhance').onclick;$('enhance').onclick=guarded(async()=>{const provider=$('cloudProvider').value;if(provider==='local')return localEnhance();if(!current)throw Error('Select a portrait first');if(!app.settings[provider+'_connected']){ $('settings').click();throw Error('Add an API key in Settings first') }if(!confirm('Send this portrait and your prompt to '+(provider==='openai'?'OpenAI':'Gemini')+' for enhancement? API charges may apply. The result may change facial details; review before saving.'))return;await run('/api/cloud-enhance',{provider,cloud_model:app.settings[provider+'_model']||(provider==='openai'?'gpt-image-1':'gemini-3.1-flash-image'),prompt:localStorage.getItem('glass-prompt')||app.prompt})});
$('applyCutouts').onclick=()=>{if(!batch?.files.length){message('Add portraits first');return}show('batchDialog')};
$('startBatch').onclick=guarded(async()=>{await flush();const scale=$('upscale').value;await api('/api/batch-process',{color:$('batchColor').checked,enhance:$('batchEnhance').checked,cutout:$('batchCutout').checked,scale:scale==='auto'?1:Number(scale),amount:Number($('detailAmount').value)});$('batchDialog').close();await refresh()});
for(const b of document.querySelectorAll('[data-dismiss]'))b.onclick=()=>b.closest('dialog').close();
async function resolveDestination(){const status=await api('/api/destination-status');if(!status.exists){$('overwrite').checked=false;return 'add'}$('folderConflictPath').textContent=status.path;const choice=await new Promise(resolve=>{const dialog=$('folderDialog');const close=()=>{dialog.removeEventListener('close',close);resolve(dialog.returnValue||'cancel')};dialog.returnValue='cancel';dialog.addEventListener('close',close);for(const b of dialog.querySelectorAll('[data-folder]'))b.onclick=()=>dialog.close(b.dataset.folder);dialog.showModal()});if(choice==='cancel')return null;if(choice==='rename'){const name=prompt('New folder name:',$('subfolder').value);if(!name)return null;$('subfolder').value=name;await api('/api/output',{subfolder:name});return resolveDestination()}$('overwrite').checked=choice==='replace';return choice}
const previousOutput=renderOutput;renderOutput=function(){previousOutput();$('destinationPath').textContent=[$('finalFolder').value.replace(/\/$/,''),$('subfolder').value].filter(Boolean).join('/')};
for(const id of ['finalFolder','subfolder'])$(id).addEventListener('input',()=>{$('destinationPath').textContent=[$('finalFolder').value.replace(/\/$/,''),$('subfolder').value].filter(Boolean).join('/')});
legacyShortcut('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable=true]')||document.querySelector('dialog[open]'))return;const map={b:'keep',e:'remove',v:'move'};if(!e.metaKey&&!e.ctrlKey&&map[e.key.toLowerCase()]){e.preventDefault();document.querySelector('[data-brush="'+map[e.key.toLowerCase()]+'"]').click()}if((e.metaKey||e.ctrlKey)&&['+','=','-','_'].includes(e.key)){e.preventDefault();$('brushSize').value=Math.max(2,Math.min(200,Number($('brushSize').value)+(['+','='].includes(e.key)?5:-5)));$('brushSize').oninput()}});
// Source-space crop editor with draggable corner handles.
let cropBox=null,cropDrag=null;
function cropDraw(){const c=$('cropCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(workImg,0,0,c.width,c.height);const [l,t,r,b]=cropBox;ctx.fillStyle='#0009';ctx.fillRect(0,0,c.width,t*c.height);ctx.fillRect(0,b*c.height,c.width,(1-b)*c.height);ctx.fillRect(0,t*c.height,l*c.width,(b-t)*c.height);ctx.fillRect(r*c.width,t*c.height,(1-r)*c.width,(b-t)*c.height);ctx.strokeStyle='#cbb6ff';ctx.lineWidth=2;ctx.strokeRect(l*c.width,t*c.height,(r-l)*c.width,(b-t)*c.height);ctx.fillStyle='#eee5ff';for(const [x,y] of [[l,t],[r,t],[r,b],[l,b]])ctx.fillRect(x*c.width-6,y*c.height-6,12,12)}
$('crop').onclick=guarded(async()=>{if(!current)return;await flush();const c=$('cropCanvas'),scale=Math.min(1,800/current.width,550/current.height);c.width=current.width*scale;c.height=current.height*scale;cropBox=[.05,.05,.95,.95];show('cropDialog');cropDraw()});
function cropPoint(e){const rect=$('cropCanvas').getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))]}
$('cropCanvas').onpointerdown=e=>{const p=cropPoint(e),[l,t,r,b]=cropBox,corners=[[l,t],[r,t],[r,b],[l,b]];cropDrag=corners.map(q=>Math.hypot(q[0]-p[0],q[1]-p[1])).reduce((best,d,i,arr)=>d<arr[best]?i:best,0);$('cropCanvas').setPointerCapture(e.pointerId)};
$('cropCanvas').onpointermove=e=>{if(cropDrag===null)return;const [x,y]=cropPoint(e);if(cropDrag===0||cropDrag===3)cropBox[0]=Math.min(x,cropBox[2]-.02);else cropBox[2]=Math.max(x,cropBox[0]+.02);if(cropDrag<2)cropBox[1]=Math.min(y,cropBox[3]-.02);else cropBox[3]=Math.max(y,cropBox[1]+.02);cropDraw()};
$('cropCanvas').onpointerup=$('cropCanvas').onpointercancel=()=>cropDrag=null;
$('applyCrop').onclick=guarded(async()=>{await api('/api/crop',context({box:cropBox.map((v,i)=>v*(i%2?current.height:current.width))}));$('cropDialog').close();await refresh(true);message('Crop applied. Undo restores the previous image and mask.')});
