// Panel sizing and precise mask corrections.
const resetAllColor=$('neutralColor');resetAllColor.textContent='Reset';resetAllColor.title='Reset all color adjustments';resetAllColor.setAttribute('aria-label','Reset color');resetAllColor.className='';$('autoColor').before(resetAllColor);
const colorHeader=$('autoColor').parentElement;colorHeader.classList.add('colorHeaderActions');
const lassoButton=makeButton('lassoTool','<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 17C2 15 2 8 6 5C10 1 21 4 21 10C21 16 12 19 7 17C4 16 5 13 7 13C11 13 9 21 5 22"/></svg>','Lasso (L)');lassoButton.dataset.brush='lasso';$('lockPosition').before(lassoButton);lassoButton.onclick=()=>{brush='lasso';for(const b of document.querySelectorAll('[data-brush]'))b.classList.toggle('active',b===lassoButton);setMode('mask');updateBrushCursor()};
const maskTools=document.createElement('div');maskTools.className='maskToolOptions';maskTools.innerHTML='<label>Brush hardness <input id="brushHardness" type="range" min="0" max="100" value="85"><output id="hardnessValue">85%</output></label><label>Lasso <select id="lassoMode"><option value="remove">Remove inside</option><option value="keep">Keep inside</option></select></label><label>Feather <input id="lassoFeather" type="number" min="0" max="30" value="0"> px</label>';document.querySelector('.brushbar').after(maskTools);$('brushHardness').title='0% soft edge · 100% hard edge';$('brushHardness').oninput=()=>$('hardnessValue').textContent=$('brushHardness').value+'%';
legacyShortcut('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable=true]')||document.querySelector('dialog[open]'))return;if(e.key==='Escape'&&stroke){stroke=null;draw()}if(!e.metaKey&&!e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();lassoButton.click()}});
// Keep quality choices beside the operation, rather than buried in Settings.
const models=[['birefnet-portrait','Portrait detail'],['birefnet-general','Full general detail'],['u2netp','Fast preview']];for(const id of ['detectionProfile','maskModel']){const select=$(id),old=select.value;select.replaceChildren(...models.map(([value,label])=>new Option(label,value)));select.value=(models.some(([value])=>value===old)?old:'')||'birefnet-portrait'}
const maskChoice=document.createElement('label');maskChoice.className='qualityChoice';maskChoice.append('Cutout model ', $('detectionProfile'));document.querySelector('.maskSection .two').before(maskChoice);
const edgeQuick=makeButton('edgeQuick','Refine hair & edges','Refine hair and remove color fringes');edgeQuick.onclick=()=>$('edgeOptions').click();document.querySelector('.maskSection').append(edgeQuick);
const engineChoice=document.createElement('label');engineChoice.className='qualityChoice';engineChoice.append('Enhancement ', $('cloudProvider'));document.querySelector('.enhanceRow').before(engineChoice);$('cloudProvider').options[0].textContent='Local · sharpen / upscale';
const detailHelp=document.createElement('p');detailHelp.className='qualityHelp';detailHelp.textContent='Detail only sharpens existing pixels. Choose 2× or 4× for local upscaling, or a connected AI service to reconstruct detail. Review AI results for identity changes.';document.querySelector('.enhanceRow').after(detailHelp);

const qualityCutoutLabel=document.createElement('label');qualityCutoutLabel.className='check qualityCutout';qualityCutoutLabel.innerHTML='<input type="checkbox" id="qualityCutout">Refine hair & remove color fringes';document.querySelector('.maskSection .two').before(qualityCutoutLabel);$('qualityCutout').onchange=guarded(async()=>{await api('/api/settings',{quality_cutout:$('qualityCutout').checked});await refresh()});const renderQuality=renderOutput;renderOutput=function(){renderQuality();$('qualityCutout').checked=app.settings.quality_cutout!==false;$('qualityCutout').disabled=busy};
const faceRestoreLabel=document.createElement('label');faceRestoreLabel.className='check faceRestore';faceRestoreLabel.title='Runs an additional face-specific restoration pass (GFPGAN) after Enhance. Experimental: review the result.';faceRestoreLabel.innerHTML='<input type="checkbox" id="faceRestore">Restore faces';document.querySelector('.detailSection .sliderRow').before(faceRestoreLabel);$('faceRestore').onchange=guarded(async()=>{await api('/api/settings',{face_restore:$('faceRestore').checked});await refresh()});const renderFaceRestore=renderOutput;renderOutput=function(){renderFaceRestore();$('faceRestore').checked=app.settings.face_restore===true;$('faceRestore').disabled=busy};
