/* Keep established control IDs while applying the approved Clarette layout. */
const el=id=>document.getElementById(id);
const icon=(name)=>feather.icons[name].toSvg({'aria-hidden':'true',width:22,height:22});
const buttonIcon=(id,name,label,only=false)=>{el(id).innerHTML=icon(name)+(only?'':'<span>'+label+'</span>');el(id).title=label;el(id).setAttribute('aria-label',label)};
buttonIcon('chatgpt','message-circle','ChatGPT');buttonIcon('gemini','star','Gemini');buttonIcon('copyPrompt','copy','Prompt');buttonIcon('photoshop','edit','Photoshop');buttonIcon('help','help-circle','Help');buttonIcon('settings','settings','Settings');
el('working').hidden=true;el('apiKeys').hidden=true;
const foot=document.querySelector('.batchFoot');foot.innerHTML='<span id="savedCount"></span><div class="portraitActions"></div><button id="applyCutouts">Apply to All…</button><button id="newBatch" hidden>New batch</button>';
foot.querySelector('.portraitActions').append(el('importBtn'));
const clear=document.createElement('button');clear.id='clearPortraits';foot.querySelector('.portraitActions').append(clear);
buttonIcon('importBtn','image','Add images');buttonIcon('clearPortraits','trash-2','Clear');
el('emptyImport').hidden=true;el('empty').querySelector('h2').textContent='A little clarity. A lot of you.';el('empty').querySelector('p').textContent='Add portraits to begin your next batch.';
el('before').innerHTML=icon('eye')+'<span>Hold for original</span>';el('before').title='Hold to view the original imported image';el('before').setAttribute('aria-label','Hold for original');
const cut=document.createElement('button');cut.id='cutoutToggle';cut.innerHTML=icon('grid')+'<span>Cutout preview</span>';cut.setAttribute('aria-pressed','false');el('before').after(cut);
el('views').hidden=true;el('guide').closest('label').classList.add('guideToggle');
const tools=document.createElement('div');tools.className='canvasTools';document.querySelector('.previews').prepend(tools);
const crop=document.createElement('button');crop.id='crop';crop.innerHTML=icon('crop');crop.title='Crop';crop.setAttribute('aria-label','Crop');tools.append(crop,el('brushTools'));
for(const b of el('brushTools').children){const type=b.dataset.brush;const names={move:['move','Move (V)'],keep:['edit-3','Brush (B)'],remove:['delete','Erase (E)'],refine:['feather','Refine hair']};b.innerHTML=icon(names[type][0]);b.title=names[type][1];b.setAttribute('aria-label',names[type][1]);}
el('brushSize').parentElement.firstChild.textContent='Brush Size ';buttonIcon('undo','rotate-ccw','Undo',true);
const position=el('autoFit').closest('section');const fit=document.createElement('div');fit.className='fitControls';fit.append(el('autoFit'),el('headBox'),el('guide').closest('label'));document.querySelector('.viewbar').prepend(fit);
buttonIcon('autoFit','sliders','Auto Fit to Guide');buttonIcon('headBox','maximize','Manual Fit');
const posDetails=document.createElement('details');posDetails.innerHTML='<summary>Position adjustments</summary>';position.before(posDetails);posDetails.append(position);
const detail=el('enhance').closest('section');detail.classList.add('detailSection');detail.querySelector('.sectionTitle span').textContent='Detail';
const drop=document.createElement('button');drop.id='enhanceDrop';drop.className='uploadZone';drop.innerHTML=icon('upload')+'<strong>Drop an enhanced image here</strong><span>or click to browse</span>';detail.querySelector('.sectionTitle').after(drop);el('replaceWorking').hidden=true;
const cloud=document.createElement('div');cloud.className='cloudControls';cloud.innerHTML='<select id="cloudProvider" aria-label="Enhancement engine"><option value="local">Local enhancement</option><option value="openai">OpenAI API</option><option value="gemini">Gemini API</option></select>';detail.querySelector('.two').before(cloud);
const maskSection=document.createElement('section');maskSection.innerHTML='<div class="sectionTitle"><span>Mask</span></div><div class="two maskButtons"></div>';maskSection.querySelector('.two').append(el('detectMask'),el('applyMask'));maskSection.append(el('detectionProfile'),el('edgeOptions'));detail.after(maskSection);
document.querySelector('.cutoutActions').hidden=true;el('presets').textContent='Output size';document.querySelector('.inspectorTabs b').textContent='Enhance';
// One output row, with a full path underneath.
buttonIcon('openFinal','folder','Open final folder',true);el('saveFinals').before(el('openFinal'));el('openFinal').classList.remove('textButton');el('saveFinals').textContent='Save finals';
const path=document.createElement('div');path.id='destinationPath';document.querySelector('.deliveryRow').after(path);el('overwrite').closest('label').hidden=true;
// API controls live inside Settings. Old placeholder dialog remains hidden for legacy IDs.
const apiSection=document.createElement('section');apiSection.className='apiSettings';apiSection.innerHTML='<h3>AI connections</h3><p>Keys are stored in macOS Keychain. Cloud enhancement sends only the selected portrait and prompt to the chosen provider when you confirm it.</p>'+['openai','gemini'].map(p=>`<fieldset><legend>${p==='openai'?'OpenAI':'Gemini'} <span id="${p}Status"></span></legend><label>API key<input id="${p}Key" type="password" autocomplete="off" placeholder="Paste a key to save or replace it"></label><label>Image model<input id="${p}Model" value="${p==='openai'?'gpt-image-1':'gemini-3.1-flash-image'}"></label><div class="two"><button id="${p}Save">Save key</button><button id="${p}Test">Test connection</button><button id="${p}Remove">Remove key</button></div></fieldset>`).join('');
el('settingsDialog').querySelector('hr').before(apiSection);
el('helpDialog').insertAdjacentHTML('beforeend','<h3>Portrait stages</h3><p class="stageLegend"><span data-stage="original">Original</span><span data-stage="editing">Editing</span><span data-stage="masking">Masking</span><span data-stage="cutout">Cutout</span><span data-stage="saved">Saved</span></p><p>B: Brush · E: Erase · V: Move · ⌘ + / ⌘ −: Brush size. Hold the eye button for your original import. Cutout preview stays editable. Crop resets the mask; Undo restores it.</p>');
document.body.insertAdjacentHTML('beforeend',`<dialog id="batchDialog"><div class="dialogHead"><h2>Apply to All</h2><button data-dismiss>Cancel</button></div><p>Process every portrait in the current batch. Completed portraits remain saved in your session if you cancel.</p><label class="check"><input id="batchColor" type="checkbox" checked>Auto Color</label><label class="check"><input id="batchEnhance" type="checkbox">Enhance detail</label><label class="check"><input id="batchCutout" type="checkbox" checked>Detect and apply cutout</label><p>Uses local processing and the current detail strength, upscale factor, and mask model.</p><button id="startBatch" class="primary">Process portraits</button></dialog><dialog id="folderDialog"><h2>This folder already exists</h2><p id="folderConflictPath"></p><p>Replace keeps the old folder beside it as a dated backup.</p><div class="dialogFoot"><button data-folder="cancel">Cancel</button><button data-folder="rename">Rename</button><button data-folder="replace">Replace folder</button><button data-folder="add" class="primary">Add files</button></div></dialog><dialog id="cropDialog"><div class="dialogHead"><h2>Crop portrait</h2><button data-dismiss>Cancel</button></div><p>Drag the corner handles. Cropping resets the mask; Undo restores it.</p><canvas id="cropCanvas"></canvas><button id="applyCrop" class="primary">Apply crop</button></dialog>`);

const colorSection=el('autoColor').closest('section');colorSection.querySelector('.sectionTitle span').textContent='Color';
const cg=document.createElement('div');cg.className='colorGrid';const adjustments=document.createElement('div');adjustments.className='balanceControls';
for(const [id,label] of [['temperature','White balance'],['tint','Tint']])adjustments.insertAdjacentHTML('beforeend',`<div class="sliderRow"><label for="${id}">${label}</label><input id="${id}" type="range" min="-100" max="100" value="0"><output id="${id}Out">0</output></div>`);
adjustments.append(el('shadows').closest('.sliderRow'),el('highlights').closest('.sliderRow'));colorSection.querySelector('.curveBox').before(cg);cg.append(colorSection.querySelector('.curveBox'),adjustments);
const advancedColor=document.createElement('details');advancedColor.className='advancedColor';advancedColor.innerHTML='<summary>More color adjustments</summary>';advancedColor.append(el('hue').closest('.sliderRow'),el('saturation').closest('.sliderRow'),el('neutralColor'));colorSection.append(advancedColor);
const detailInfo=document.createElement('details');detailInfo.innerHTML='<summary>Detail options</summary>';for(const p of Array.from(detail.querySelectorAll('p')))detailInfo.append(p);detailInfo.append(el('resetSource'));detail.append(detailInfo);
el('enhance').textContent='Enhance Portrait';el('autoColor').textContent='Auto Color';
el('helpDialog').querySelector('.stageLegend').style.display='';
