// Clarette 0.9.2: inspection, positioning, guides and live controls.
let guideEditing=false,guideDraft=null,guideDrag=null;
function queueLiveColor(){colorInteracting=true;clearTimeout(queueLiveColor.settle);if(!queueLiveColor.frame)queueLiveColor.frame=requestAnimationFrame(()=>{queueLiveColor.frame=null;syncColor();updatePreview()});queueLiveColor.settle=setTimeout(()=>{colorInteracting=false;updatePreview();schedule()},130)}
function makeButton(id,icon,label){const b=document.createElement('button');b.id=id;b.innerHTML=icon;b.title=label;b.setAttribute('aria-label',label);return b}
const lockGlyph='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 018 0v4M12 14v3"/></svg>';
const lockPosition=makeButton('lockPosition',lockGlyph,'Lock headshot position');lockPosition.setAttribute('aria-pressed','false');$('brushTools').append(lockPosition);
lockPosition.onclick=guarded(async()=>{await flush();await api('/api/edit',context({position_locked:!current.position_locked}));await refresh(true);syncWorkflow();message(current.position_locked?'Position locked. Drag or scroll to inspect; export size stays fixed.':'Position unlocked')});
// Both comparison controls retain accessible labels and tooltips.
for(const option of $('upscale').options)option.textContent=option.textContent.replace(' neural',' upscale');
for(const id of ['before','cutoutToggle']){$(id).querySelectorAll('span').forEach(e=>e.remove());$(id).classList.add('comparisonIcon')}
$('before').title='Hold for original · same placement and scale';
const tintRow=$('tint').closest('.sliderRow'),saturationRow=$('saturation').closest('.sliderRow');tintRow.before(saturationRow);document.querySelector('.advancedColor').append(tintRow);
const enhanceRow=document.createElement('div');enhanceRow.className='enhanceRow';$('enhance').before(enhanceRow);enhanceRow.append($('enhance'),$('working'));$('working').hidden=false;$('working').innerHTML=phosphor.folder;$('working').title='Open Working Folder';$('working').setAttribute('aria-label','Open Working Folder');
// Inspection controls never mutate the headshot transform.
const zoomTrigger=makeButton('viewControls',phosphor['magnifying-glass-plus'],'Preview zoom and position');document.querySelector('.zoomIcon').replaceWith(zoomTrigger);
const homeView=makeButton('homeView','<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10L12 3L21 10M5 9V21H10V14H14V21H19V9"/></svg>','Home · Fit output');zoomTrigger.before(homeView);homeView.onclick=()=>{$('fitInspection').onclick()};
const viewSlider=document.createElement('input');viewSlider.type='range';viewSlider.min='5';viewSlider.max='600';viewSlider.step='1';viewSlider.id='inspectionZoom';viewSlider.setAttribute('aria-label','Preview zoom percent');$('viewZoom').after(viewSlider);
const viewPanel=document.createElement('dialog');viewPanel.id='viewPanel';viewPanel.innerHTML='<div class="dialogHead"><h2>View & Position</h2><button data-view-close>Close</button></div><div class="fieldGrid"><label>View zoom %<input id="viewPercent" type="number" min="5" max="600" step="1"></label><label>View X (px)<input id="viewPanX" type="number"></label><label>View Y (px)<input id="viewPanY" type="number"></label></div><button id="fitInspection">Fit output</button><hr><h3>Image Placement</h3><p id="placementNote" hidden></p><div class="fieldGrid"><label>Scale %<input id="placementScale" type="number" min="0.1" max="10000" step="0.1"></label><label>X (px)<input id="placementX" type="number"></label><label>Y (px)<input id="placementY" type="number"></label></div>';document.body.append(viewPanel);
viewPanel.querySelector('[data-view-close]').onclick=()=>viewPanel.close();viewPanel.addEventListener('close',()=>{zoomTrigger.classList.remove('active');zoomTrigger.setAttribute('aria-expanded','false');zoomTrigger.focus({preventScroll:true})});viewPanel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();viewPanel.close()}});zoomTrigger.onclick=()=>{if(!current)return;syncWorkflow();viewPanel.show();zoomTrigger.setAttribute('aria-expanded','true');if(!viewPanel.dataset.positioned){const r=zoomTrigger.getBoundingClientRect();viewPanel.style.left=Math.max(14,Math.min(innerWidth-viewPanel.offsetWidth-14,r.left))+'px';viewPanel.style.top=Math.max(14,Math.min(innerHeight-viewPanel.offsetHeight-14,r.top-viewPanel.offsetHeight-12))+'px';viewPanel.dataset.positioned='true'}};
function setInspectionZoom(k,anchor){if(!batch)return;const c=$('mainCanvas'),g=geometry(c);k=Math.max(.05,Math.min(6,k));const a=anchor||{x:g.w/2,y:g.h/2},px=(a.x-g.ox)/g.k,py=(a.y-g.oy)/g.k;let option=$('customZoom');if(!option){option=new Option('Custom','');option.id='customZoom';$('viewZoom').add(option)}option.value=String(k);option.textContent=Math.round(k*100)+'%';$('viewZoom').value=String(k);viewShift={x:a.x-px*k-(g.w-batch.canvas.width*k)/2,y:a.y-py*k-(g.h-batch.canvas.height*k)/2};draw();syncWorkflow()}
viewSlider.oninput=()=>setInspectionZoom(Number(viewSlider.value)/100);$('viewPercent').oninput=()=>{if($('viewPercent').value)setInspectionZoom(Number($('viewPercent').value)/100)};
for(const [id,key] of [['viewPanX','x'],['viewPanY','y']])$(id).oninput=()=>{viewShift[key]=Number($(id).value)||0;draw()};
$('fitInspection').onclick=()=>{$('viewZoom').value='fit';viewShift={x:0,y:0};draw();syncWorkflow()};const previousZoomChange=$('viewZoom').onchange;$('viewZoom').onchange=()=>{previousZoomChange();syncWorkflow()};
for(const id of ['placementScale','placementX','placementY'])$(id).onchange=guarded(async()=>{if(!current||current.position_locked)return;const scale=Number($('placementScale').value)/100,x=Number($('placementX').value),y=Number($('placementY').value);if(![scale,x,y].every(Number.isFinite)||scale<.001||scale>100)throw Error('Enter a valid image position and scale');current.transform={scale,x,y};syncPosition();draw();schedule()});
// Stretch the ellipse and position the eye line directly over the preview.
const editGuide=makeButton('editGuide',phosphor['sliders-horizontal'],'Customize face guide');document.querySelector('.guideToggle').after(editGuide);
const guidePanel=document.createElement('div');guidePanel.id='guideEditor';guidePanel.hidden=true;guidePanel.innerHTML='<strong>Face guide</strong><span>Drag the sides, top or chin to reshape. Drag the center to move; drag the eye line to align.</span><div><button id="useGuide">Use guide</button><button id="defaultGuide" class="primary">Save as default</button><button id="cancelGuide">Cancel</button></div>';document.querySelector('.historyTools').after(guidePanel);
function activeGuide(){return guideDraft||batch?.canvas.guide||{cx:.5,top:batch?.canvas.headTop??.035,width:batch?.canvas.headW||.255,height:Math.min(.95,(batch?.canvas.width||2048)*(batch?.canvas.headW||.255)*1.18/(batch?.canvas.height||1024)),eyes:.45}}
function guideCoordinates(){const g=activeGuide(),c=batch.canvas,v=geometry($('mainCanvas'));return {v,g,cx:v.ox+g.cx*c.width*v.k,top:v.oy+g.top*c.height*v.k,w:g.width*c.width*v.k,h:g.height*c.height*v.k}}
function drawGuide(ctx,v,w,h){const g=activeGuide(),c=batch.canvas,cx=v.ox+g.cx*c.width*v.k,top=v.oy+g.top*c.height*v.k,gw=g.width*c.width*v.k,gh=g.height*c.height*v.k,eye=top+gh*g.eyes;ctx.save();ctx.beginPath();ctx.rect(v.ox,v.oy,c.width*v.k,c.height*v.k);ctx.clip();ctx.strokeStyle=guideEditing?'#d1b8ff':'#bda1edbb';ctx.lineWidth=guideEditing?1.6:1;ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(cx,v.oy);ctx.lineTo(cx,v.oy+c.height*v.k);ctx.moveTo(cx-gw*.75,eye);ctx.lineTo(cx+gw*.75,eye);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.ellipse(cx,top+gh/2,gw/2,gh/2,0,0,Math.PI*2);ctx.stroke();if(guideEditing){ctx.font='11px -apple-system,sans-serif';ctx.fillStyle='#e5d8ff';ctx.fillText('Eyes',cx+gw/2+6,eye-5);ctx.fillText('Chin',cx+7,top+gh-7);for(const [x,y] of [[cx-gw/2,top+gh/2],[cx+gw/2,top+gh/2],[cx,top],[cx,top+gh],[cx,eye],[cx,top+gh/2]]){ctx.fillStyle='#b49af4';ctx.fillRect(x-5,y-5,10,10);ctx.strokeStyle='#f0e8ff';ctx.strokeRect(x-5,y-5,10,10)}}ctx.restore()}
editGuide.onclick=()=>{if(!batch)return;guideDraft=clone(activeGuide());guideEditing=true;guidePanel.hidden=false;guidePanel.querySelector('strong').textContent='Face guide · '+batch.canvas.width+' × '+batch.canvas.height+' px';draw()};
for(const [id,saveDefault] of [['useGuide',false],['defaultGuide',true]])$(id).onclick=guarded(async()=>{await api('/api/guide',{guide:guideDraft,save_default:saveDefault});guideEditing=false;guideDraft=null;guidePanel.hidden=true;await refresh();draw();message(saveDefault?'Default guide saved for this output size. Auto Fit will follow it.':'Face guide updated')});
$('cancelGuide').onclick=()=>{guideEditing=false;guideDraft=null;guidePanel.hidden=true;draw()};
const canvasDown=$('mainCanvas').onpointerdown,canvasMove=$('mainCanvas').onpointermove,canvasUp=$('mainCanvas').onpointerup,canvasCancel=$('mainCanvas').onpointercancel;
$('mainCanvas').onpointerdown=e=>{if(!guideEditing)return canvasDown(e);const r=$('mainCanvas').getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top},q=guideCoordinates(),handles=[['eyes',q.cx,q.top+q.h*q.g.eyes],['left',q.cx-q.w/2,q.top+q.h/2],['right',q.cx+q.w/2,q.top+q.h/2],['top',q.cx,q.top],['chin',q.cx,q.top+q.h],['center',q.cx,q.top+q.h/2]],hit=handles.find(([,x,y])=>Math.hypot(x-p.x,y-p.y)<16);if(!hit)return;guideDrag={kind:hit[0],x:e.clientX,y:e.clientY,start:clone(guideDraft),k:q.v.k};$('mainCanvas').setPointerCapture(e.pointerId)};
$('mainCanvas').onpointermove=e=>{if(!guideEditing)return canvasMove(e);if(!guideDrag)return;const {start:s,kind,k}=guideDrag,dx=(e.clientX-guideDrag.x)/(batch.canvas.width*k),dy=(e.clientY-guideDrag.y)/(batch.canvas.height*k),g=clone(s);if(kind==='center'){g.cx=Math.max(g.width/2,Math.min(1-g.width/2,s.cx+dx));g.top=Math.max(0,Math.min(1-g.height,s.top+dy))}if(kind==='left'||kind==='right')g.width=Math.max(.03,Math.min(2*Math.min(g.cx,1-g.cx),s.width+(kind==='right'?2:-2)*dx));if(kind==='chin')g.height=Math.max(.03,Math.min(1-g.top,s.height+dy));if(kind==='top'){g.top=Math.max(0,Math.min(s.top+s.height-.03,s.top+dy));g.height=s.height+s.top-g.top}if(kind==='eyes')g.eyes=Math.max(.1,Math.min(.9,s.eyes+dy/s.height));guideDraft=g;draw()};
$('mainCanvas').onpointerup=e=>{if(guideEditing){guideDrag=null;return}return canvasUp(e)};$('mainCanvas').onpointercancel=e=>{guideDrag=null;return canvasCancel(e)};
// Native app notifications use its bundle icon; sound is independent and opt-in.
const soundLabel=document.createElement('label');soundLabel.className='check';soundLabel.innerHTML='<input id="notificationSound" type="checkbox">Play a notification sound';$('notifications').closest('label').after(soundLabel);const testNotice=makeButton('testNotification','Test notification','Test notification');soundLabel.after(testNotice);
const methodLabel=document.createElement('label');methodLabel.innerHTML='Upscale method<select id="upscaleMethod"><option value="neural">Neural quality · EDSR</option><option value="fast">Fast resize · Lanczos + detail</option></select><small>Fast resize preserves existing detail; it does not infer new detail with a neural model.</small>';$('cloudProvider').parentElement.after(methodLabel);
$('notificationSound').onchange=guarded(async()=>{await api('/api/settings',{notification_sound:$('notificationSound').checked});await refresh()});$('upscaleMethod').onchange=guarded(async()=>{await api('/api/settings',{upscale_method:$('upscaleMethod').value});await refresh()});testNotice.onclick=guarded(async()=>{const r=await api('/api/notification-test');message(r.sound_played?'Sound playback completed.':'Audio playback failed. If using the browser preview, try Play in the standalone Clarette app. Otherwise check your Mac’s sound output.')});
const settingsOpen092=$('settings').onclick;$('settings').onclick=()=>{settingsOpen092();$('notificationSound').checked=!!app.settings.notification_sound;$('upscaleMethod').value=app.settings.upscale_method||'neural'};
// Move dialogs by their heading; form fields retain normal interactions.
function movableDialog(dialog){const header=dialog.querySelector('.dialogHead');if(!header)return;header.classList.add('dragHandle');header.title='Drag to move';let moving=null;header.addEventListener('pointerdown',e=>{if(e.target.closest('button,input,select,textarea')||e.button!==0)return;const r=dialog.getBoundingClientRect();dialog.style.margin='0';dialog.style.inset='auto';dialog.style.left=r.left+'px';dialog.style.top=r.top+'px';moving={x:e.clientX,y:e.clientY,left:r.left,top:r.top};header.setPointerCapture(e.pointerId)});header.addEventListener('pointermove',e=>{if(!moving)return;dialog.style.left=Math.max(0,Math.min(window.innerWidth-80,moving.left+e.clientX-moving.x))+'px';dialog.style.top=Math.max(0,Math.min(window.innerHeight-50,moving.top+e.clientY-moving.y))+'px'});for(const event of ['pointerup','pointercancel'])header.addEventListener(event,()=>moving=null)}movableDialog($('settingsDialog'));movableDialog(viewPanel);
function syncWorkflow(){const locked=!!current?.position_locked;lockPosition.classList.toggle('active',locked);lockPosition.setAttribute('aria-pressed',String(locked));lockPosition.title=locked?'Unlock headshot position':'Lock headshot position';for(const id of ['placementScale','placementX','placementY','scale','scaleNumber','positionX','positionXNumber','positionY','positionYNumber','resetPosition','autoFit','headBox'])$(id).disabled=busy||locked||!current;if(!current||!batch)return;const g=geometry($('mainCanvas'));viewSlider.value=Math.round(g.k*100);for(const [id,value] of [['viewPercent',Math.round(g.k*100)],['viewPanX',Math.round(viewShift.x)],['viewPanY',Math.round(viewShift.y)],['placementScale',+(current.transform.scale*100).toFixed(2)],['placementX',Math.round(current.transform.x)],['placementY',Math.round(current.transform.y)]])if(document.activeElement!==$(id))$(id).value=value;$('placementNote').textContent=locked?'Position is locked. Unlock it in the toolbar to edit placement.':'These values change the headshot placement in the final image.'}
const jobs092=renderJobs;renderJobs=function(){jobs092();syncWorkflow()};const loaded092=loadSelected;loadSelected=async function(){await loaded092();syncWorkflow()};
const originalHeadFit=$('useHead').onclick;$('useHead').onclick=()=>{if(current.position_locked)return;const c=batch.canvas,g=activeGuide(),r=headRect,s=Math.min(g.width*c.width/(r.w*current.width),g.height*c.height/(r.h*current.height));current.transform={scale:s,x:g.cx*c.width-(r.x+r.w/2)*current.width*s,y:(g.top+g.height)*c.height-(r.y+r.h)*current.height*s};$('headDialog').close();syncPosition();draw();schedule()};

for(const id of ['presetSelect','canvasWidth','canvasHeight','dpi'])$(id).addEventListener('change',()=>{guideEditing=false;guideDraft=null;guideDrag=null;guidePanel.hidden=true});

const presetTransfer=document.createElement('section');presetTransfer.className='presetTransfer';presetTransfer.innerHTML='<h3>Output sizes & guides</h3><p>Choose which presets to share. New presets are added; existing presets require confirmation before replacement.</p><div class="two"><button id="importOutputPresets">Import output presets</button><button id="exportOutputPresets">Export output presets</button></div><input id="outputPresetFile" type="file" accept="application/json,.json" hidden>';$('settingsDialog').querySelector('hr').after(presetTransfer);
const transferDialog=document.createElement('dialog');transferDialog.id='presetTransferDialog';transferDialog.innerHTML='<div class="dialogHead"><h2 id="transferTitle">Output presets</h2><button id="transferClose">Cancel</button></div><p id="transferHint"></p><div id="transferList"></div><button id="transferGo" class="primary">Continue</button>';document.body.append(transferDialog);$('transferClose').onclick=()=>transferDialog.close();
function selectTransfer(mode,entries,document){let replacementSelection=null;$('transferTitle').textContent=mode==='export'?'Export output presets':'Import output presets';$('transferHint').textContent=mode==='export'?'Select the output sizes and their guides to export.':'Select presets to import. Existing presets are marked below.';$('transferList').replaceChildren();for(const e of entries){const row=window.document.createElement('label');row.className='transferRow';const box=window.document.createElement('input');box.type='checkbox';box.checked=true;box.value=String(mode==='export'?e.id:e.index);const text=window.document.createElement('span');text.textContent=e.label+' · '+e.width+' × '+e.height+' · '+e.dpi+' dpi'+(e.existing_id?' — replaces existing':'');row.append(box,text);$('transferList').append(row)}$('transferGo').textContent=mode==='export'?'Export selected':'Import selected';$('transferGo').onclick=guarded(async()=>{const selected=[...$('transferList').querySelectorAll('input:checked')].map(x=>x.value);if(!selected.length)throw Error('Select at least one output preset');if(mode==='export'){const r=await api('/api/output-presets-export',{selected_ids:selected});if(r.cancelled)return;if(r.document){const url=URL.createObjectURL(new Blob([JSON.stringify(r.document,null,2)],{type:'application/json'}));const a=window.document.createElement('a');a.href=url;a.download='Clarette-output-presets.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}message('Selected output presets exported')}else{const chosen=selected.map(Number),existing=entries.filter(e=>chosen.includes(e.index)&&e.existing_id);if(existing.length&&replacementSelection!==JSON.stringify(chosen)){replacementSelection=JSON.stringify(chosen);$('transferHint').textContent='Replace existing settings and guides for '+existing.map(e=>e.label).join(', ')+'? Click Replace existing & import to confirm, or Cancel to keep them.';$('transferHint').setAttribute('role','alert');$('transferGo').textContent='Replace existing & import';return;}const r=await api('/api/output-presets-import',{document,selected_indexes:chosen,replace_existing:existing.map(e=>e.existing_id)});guideEditing=false;guideDraft=null;guidePanel.hidden=true;await refresh();draw();message(r.imported+' output presets imported')}transferDialog.close()});transferDialog.showModal()}
$('importOutputPresets').onclick=()=>$('outputPresetFile').click();$('outputPresetFile').onchange=guarded(async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>262144)throw Error('Preset files must be smaller than 256 KB');let document;try{document=JSON.parse(await file.text())}catch{throw Error('Choose a valid Clarette output presets JSON file')}const r=await api('/api/output-presets-preview',{document});selectTransfer('import',r.entries,document)});
$('exportOutputPresets').onclick=guarded(async()=>{await flush();const r=await api('/api/output-presets-export',{preview:true});selectTransfer('export',r.document.presets)});

const settingsFooter=document.createElement('div');settingsFooter.className='settingsFooter';settingsFooter.innerHTML='<small>v1.0.1 · Apple Silicon · Kya Studio ®</small><button id="resetSettings">Reset settings</button>';$('settingsDialog').append(settingsFooter);$('quit').closest('.dialogFoot').hidden=true;
const resetDialog=document.createElement('dialog');resetDialog.id='resetSettingsDialog';resetDialog.innerHTML='<div class="dialogHead"><h2>Reset settings?</h2><button id="cancelReset">Cancel</button></div><p>Restore processing and notification defaults. Your portraits, edits, API keys, output location and saved output presets/guides will be kept.</p><button id="confirmReset" class="primary">Reset settings</button>';document.body.append(resetDialog);$('resetSettings').onclick=()=>resetDialog.showModal();$('cancelReset').onclick=()=>resetDialog.close();$('confirmReset').onclick=guarded(async()=>{await api('/api/reset-settings',{confirmed:true});await refresh();$('maskModel').value=app.settings.model;$('notifications').checked=app.settings.notifications;$('notificationSound').checked=false;$('accelerate').checked=false;$('autoGuide').checked=true;$('upscaleMethod').value='neural';for(const name of ['openai','gemini'])$(name+'Model').value=name==='openai'?'gpt-image-1':'gemini-3.1-flash-image';resetDialog.close();message('Settings reset. Your portraits and output presets were kept.')});
const soundRow=document.createElement('div');soundRow.className='notificationSoundRow';soundLabel.before(soundRow);soundRow.append(soundLabel,testNotice);testNotice.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5L19 12L8 19Z" fill="currentColor"/></svg><span>Play</span>';testNotice.title='Test notification using the selected sound setting';testNotice.setAttribute('aria-label','Play test notification');

// One consistent, accessible dismiss control for every app-owned window.
for(const dialog of document.querySelectorAll('dialog')){
 const header=dialog.querySelector('.dialogHead');if(!header)continue;
 let close=header.querySelector('button');
 if(!close){close=document.createElement('button');close.onclick=()=>dialog.close();header.append(close)}
 close.classList.add('windowClose');close.title='Close';close.setAttribute('aria-label','Close '+(header.querySelector('h2')?.textContent||'window'));
 close.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6L18 18M18 6L6 18"/></svg>';
}
